added mul.asm and sub.asm
aslastin/ITMO-Cpp-y2019-20 pull request #1
Opened 2020-07-02 10:12 UTC by aslastin

Первая сдача asm. Сластин Александр M3139

2020-07-02 15:31 UTC, kt-cpp commented on asm/mul.asm
> +;    sum is written to r12
Поправь семантически контракт, во-первых (там не `summand` очевидно)

Во-вторых, давай в `rcx` будет лежать длина множителей и требовать чтобы место под результат было `rcx*8`

И еще давай выделим память под твои `temporary` вычисления здесь, ведь они не нужны внешнему наблюдателю

2020-07-02 15:32 UTC, kt-cpp commented on asm/mul.asm
> +                call            read_long
Считал второе число как 256 -> считай как 128, так должно быть по спецификации `mul`

2020-07-02 15:34 UTC, kt-cpp commented on asm/mul.asm
> +                call            div_long_short
Ничего не понял, но очень интересно

Зачем делить на 10 и умножать на 10? Хочу пояснений.

(не стал вчитываться, потому что ты считываешь числа 128 и 256, поэтому все может измениться)

2020-07-02 15:34 UTC, kt-cpp requested changes
Читай числа 128 и 128, отдавай результат как 256, а там дальше посмотрим

2020-07-02 15:43 UTC, aslastin commented on asm/mul.asm
> +                call            div_long_short
У меня в голове была следующая визуализация: пусть число 1 - то, на которое выделил 256 qw, а число 2 - 128 qw. Тогда представим их умножение, как умножение в столбик : 1-ое сверху, 2-ое снизу. При умножении я убираю последнюю цифру 2-ого числа (деля на 10), при этом не забываю 1-ое умножить на 10, чтобы не забыть про сдвиг в умножении. Вот так все и работает.

2020-07-03 11:51 UTC, closed without merging

2020-07-05 15:09 UTC, aslastin commented on asm/mul.asm
> +                call            div_long_short
Сейчас поменял умножение